// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ePets.Data;

#nullable disable

namespace ePets.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20221117112744_OrderItem_Added")]
    partial class OrderItemAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ePets.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AnimalTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            AnimalTypeId = 1,
                            Bio = "The bald eagle is a bird of prey found in North America. A sea eagle, it has two known subspecies and forms a species pair with the white-tailed eagle , which occupies the same niche as the bald eagle in the Palearctic. Its range includes most of Canada and Alaska, all of the contiguous United States, and northern Mexico. It is found near large bodies of open water with an abundant food supply and old-growth trees for nesting.",
                            ImageUrl = "/images/Animals/BaldEagle.jpg",
                            Name = "Bald Eagle",
                            Price = 65.989999999999995
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 5,
                            AnimalTypeId = 1,
                            Bio = "The barn owl is nocturnal over most of its range; but in Great Britain and some Pacific Islands, it also hunts by day. Barn owls specialise in hunting animals on the ground and nearly all of their food consists of small mammals, which they locate by sound, their hearing being very acute.",
                            ImageUrl = "/images/Animals/BarnOwl.jpg",
                            Name = "Barn Owl",
                            Price = 27.989999999999998
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 3,
                            AnimalTypeId = 1,
                            Bio = "Macaws are a group of New World parrots that are long-tailed and often colorful. They are popular in aviculture or as companion parrots, although there are conservation concerns about several species in the wild.",
                            ImageUrl = "/images/Animals/MacawParrot.jpg",
                            Name = "Macaw Parrot",
                            Price = 24.75
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 1,
                            AnimalTypeId = 2,
                            Bio = "Clownfish or anemonefish are fishes from the subfamily Amphiprioninae in the family Pomacentridae. Thirty species of clownfish are recognized: one in the genus Premnas, while the remaining are in the genus Amphiprion.",
                            ImageUrl = "/images/Animals/ClownFish.jpg",
                            Name = "Clown Fish",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 5,
                            AnimalTypeId = 2,
                            Bio = "There are many varieties of ornamental koi, originating from breeding that began in Niigata, Japan in the early 19th century.Several varieties are recognized by the Japanese, distinguished by coloration, patterning, and scalation.",
                            ImageUrl = "/images/Animals/KoiFish.jpg",
                            Name = "Koi Fish",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 3,
                            AnimalTypeId = 3,
                            Bio = "The Belgian Shepherd (also known as the Belgian Sheepdog, Belgian Malinois, or the Chien de Berger Belge) is a breed of medium-sized herding dog from Belgium. While predominantly considered a single breed, it is bred in four distinct varieties based on coat type and colour; the long-haired black Groenendael, the rough-haired fawn Laekenois, the short-haired fawn Malinois, and the long-haired fawn Tervuren. ",
                            ImageUrl = "/images/Animals/BelgianShepherd.jpg",
                            Name = "Belgian Sheperd",
                            Price = 17.489999999999998
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 4,
                            AnimalTypeId = 3,
                            Bio = "The Golden Retriever is a Scottish breed of retriever dog of medium size. It is characterised by a gentle and affectionate nature and a striking golden coat. It is commonly kept as a pet and is among the most frequently registered breeds in several Western countries. It is a frequent competitor in dog shows and obedience trials; it is also used as a gundog, and may be trained for use as a guide dog.",
                            ImageUrl = "/images/Animals/GoldenRetriever.jpg",
                            Name = "Golden Retriever",
                            Price = 27.989999999999998
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 5,
                            AnimalTypeId = 3,
                            Bio = "Husky is a general term for a dog used in the polar regions, primarily and specifically for work as sled dogs. It refers to a traditional northern type, notable for its cold-weather tolerance and overall hardiness. Modern racing huskies that maintain arctic breed traits (also known as Alaskan huskies) represent an ever-changing crossbreed of the fastest dogs.",
                            ImageUrl = "/images/Animals/Husky.jpg",
                            Name = "Husky",
                            Price = 32.170000000000002
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 12,
                            AnimalTypeId = 4,
                            Bio = "The name bearded dragon refers to the underside of the throat (or beard) of the lizard, which can turn black and gain weight for a number of reasons, most often as a result of stress, or if they feel threatened",
                            ImageUrl = "/images/Animals/BeardedDragon.jpg",
                            Name = "Bearded Dragon",
                            Price = 13.99
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 11,
                            AnimalTypeId = 4,
                            Bio = "The king cobra (Ophiophagus hannah) is a species of venomous elapid snake endemic to jungles in Southern and Southeast Asia. The sole member of the genus Ophiophagus, it is distinguishable from other cobras, most noticeably by its size and neck patterns",
                            ImageUrl = "/images/Animals/CobraSnake.jpg",
                            Name = "Cobra",
                            Price = 19.989999999999998
                        });
                });

            modelBuilder.Entity("ePets.Models.AnimalType", b =>
                {
                    b.Property<int>("AnimalTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalTypeId");

                    b.ToTable("AnimalTypes");

                    b.HasData(
                        new
                        {
                            AnimalTypeId = 1,
                            TypeName = "Bird"
                        },
                        new
                        {
                            AnimalTypeId = 2,
                            TypeName = "Fish"
                        },
                        new
                        {
                            AnimalTypeId = 3,
                            TypeName = "Dog"
                        },
                        new
                        {
                            AnimalTypeId = 4,
                            TypeName = "Reptile"
                        });
                });

            modelBuilder.Entity("ePets.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            AnimalId = 1,
                            Content = "Doed he really bald?"
                        },
                        new
                        {
                            CommentId = 8,
                            AnimalId = 7,
                            Content = "Does He Bite?"
                        },
                        new
                        {
                            CommentId = 2,
                            AnimalId = 1,
                            Content = "So Majestic"
                        },
                        new
                        {
                            CommentId = 9,
                            AnimalId = 8,
                            Content = "So Pretty<3"
                        },
                        new
                        {
                            CommentId = 3,
                            AnimalId = 2,
                            Content = "ho ho gang!"
                        },
                        new
                        {
                            CommentId = 10,
                            AnimalId = 8,
                            Content = "Can He Survive In The Desert?"
                        },
                        new
                        {
                            CommentId = 4,
                            AnimalId = 3,
                            Content = "Wheres captain hook LOL!"
                        },
                        new
                        {
                            CommentId = 11,
                            AnimalId = 7,
                            Content = "lets go to the beach"
                        },
                        new
                        {
                            CommentId = 5,
                            AnimalId = 4,
                            Content = "found Nemo"
                        },
                        new
                        {
                            CommentId = 12,
                            AnimalId = 9,
                            Content = "Dracarys!"
                        },
                        new
                        {
                            CommentId = 6,
                            AnimalId = 5,
                            Content = "So pretty..."
                        },
                        new
                        {
                            CommentId = 13,
                            AnimalId = 9,
                            Content = "GOT > HOTD"
                        },
                        new
                        {
                            CommentId = 7,
                            AnimalId = 6,
                            Content = "best dog ever!"
                        },
                        new
                        {
                            CommentId = 14,
                            AnimalId = 10,
                            Content = "Getting Slytherin Vibe"
                        });
                });

            modelBuilder.Entity("ePets.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ePets.Models.OrderItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ItemId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ePets.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("ePets.Models.Comment", b =>
                {
                    b.HasOne("ePets.Models.Animal", "animal")
                        .WithMany("Comments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("animal");
                });

            modelBuilder.Entity("ePets.Models.OrderItem", b =>
                {
                    b.HasOne("ePets.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ePets.Models.Order", "Order")
                        .WithMany("OrderItemsList")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ePets.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("ePets.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("ePets.Models.Animal", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ePets.Models.Order", b =>
                {
                    b.Navigation("OrderItemsList");
                });
#pragma warning restore 612, 618
        }
    }
}
